### ISSUE TITLE
make genericError context aware

### ISSUE THREAD

**Issue by scottrblock** [dvargas92495/roam-client#28]
I'd consider this a suggestion, but perhaps:
- if in dev mode, `updateActiveBlock`
- if in prod mode, `console.log` (or swallow if console.log isn't safe for the browsers you're targeting).

Assuming there's some sort of webpack ENV already available to check for this kind of thing. Curious if you think I'm way off base API design wise here.

**Comment by dvargasfuertes** [comment]
this makes sense to me! yea with webpack, we'll have access to the NODE_ENV variable being either `development` or `production` when this is being built into extensions
