### ISSUE TITLE
Structuring various methods for better discoverability

### ISSUE THREAD

**Issue by Stvad** [dvargas92495/roam-client#30]
👋 right now when you use this via npm you basically get a huge bundle of all possible methods in one namespace and that's a bit hard to navigate/discover things there.

This issues is a general request for improvement on that.

I can see a few options here:
- Create wrapper objects that group available functionality by area and expose those
- Expose internal file structures as modules in npm instead of exporting the whole thing as one namespace

**Comment by dvargasfuertes** [comment]
yea I would love to do what `date-fns` does: https://date-fns.org/

Each method you could import individually to avoid the bundle issue, just haven't gotten around to doing it yet. PRs welcome! :)

**Comment by Stvad** [comment]
Not quite sure we're talking about the same thing. What I'm talking about is more about developer experience (functionality discoverability ease of interop) vs bundle size specifically.  

Playing with an example interfaces at the end of the video here https://www.loom.com/share/45913918da67430696db56ef4954da29

**Comment by dvargasfuertes** [comment]
ah I see. You're saying to do either:

```
import { queries } from 'roam-client';
queries.method()
```
OR
```
import queries from 'roam-client/queries;`
queries.method();
```

Would you be opposed to keeping the root namespace along with the module-based one too? This to avoid a major version bump and for devs who prefer keeping it all to one? My dev experience is simply typing the first couple of characters of the method names, and vscode completes the rest as well as adding the import on top. for this reason, I'd probably lean towards option 2
