### ISSUE TITLE
Where do I get the API credentials from?

### ISSUE THREAD

**Issue by batjko** [dvargas92495/roam-client#31]
Hi there,

I'd like to use the Rest client of this package, which, I assume, allows me to access my Roam graph remotely, i.e. from an external project / service.

Based on the [documentation](https://roamresearch.com/#/app/roam-depot-developers/page/mpgy3y0p2), I should somehow have these from somewhere:
- `apiKey`
- `apiToken`

But how do I find these?

**Comment by dvargasfuertes** [comment]
These are not available for now.

This package started when they had a shorter timeline on when the remote API would be ready, so much so that there was a sandbox to test in. Now, that timeline is far more up in the air and there no longer is a sandbox

**Comment by batjko** [comment]
Ah. That fact is probably worth adding to the documentation, at least until that API is officially released?

**Comment by dvargasfuertes** [comment]
yup. Roam Client in general is criminally underdocumented right now, so am adding this to the set of changes to be made
